dist: xenial
language: c
before_install:
  - sudo add-apt-repository ppa:alexlarsson/flatpak -y
  - sudo apt-get update -q
  - sudo apt install flatpak flatpak-builder -y
  - flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install --user -y flathub org.kde.Platform/x86_64/5.12 org.kde.Sdk/x86_64/5.12

install: true 

script:
  - mkdir .build
  - cd .build
  - flatpak-builder --arch=x86_64 --force-clean build ../org.wiz.Note.json
